version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - echo "Navigating to app directory..."
      - cd projects/cloud-support-engineer-projects/project-3/globalmart-catalog
      - npm install
artifacts:
  base-directory: 'projects/cloud-support-engineer-projects/project-3/globalmart-catalog'
  files:
    - '**/*'